### ISSUE TITLE
As a business admin I want to create new products, discontinue products and restock products.

### ISSUE THREAD

**Issue by Kimi310** [Kimi310/Dunder_Mifflin_EASV#2]

**Comment by IAmVolvic** [comment]
I tested it and made some changes let me know what you think here:

https://github.com/Kimi310/Dunder_Mifflin_EASV/commit/bcc6ca5a1a6322564ddb033df4da248faae0b17d
https://github.com/Kimi310/Dunder_Mifflin_EASV/commit/c9040de0a04f5da40dd50404a0ad58ee7ad7abb1

Other then that everything works.
